repos:
  # license notice
  - repo: local
    hooks:
      - id: notice
        name: notice
        entry: poetry run python notice.py
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
  # ruff check (w/autofix)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3 # should match version in pyproject.toml
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  # ruff format
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.3 # should match version in pyproject.toml
    hooks:
      - id: ruff-format
  # # pydoclint - docstring formatting
  # - repo: https://github.com/jsh9/pydoclint
  #   rev: 0.3.8
  #   hooks:
  #     - id: pydoclint
  #       args: [--config=pyproject.toml]
