version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install poetry
      - poetry config virtualenvs.create false
      - poetry install --only base,main,docs

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: false
