# Disable sudo to speed up the builds
sudo: false

# Specify Python and versions to test
language: python
python:
  - 3.5
  - 3.6
  - 3.7

# Installation scripts
install:
  - pip install -e .
  - pip install -r lib/tests/requirements.txt

# Test script
script: pytest lib/test