name: Create GitHub release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Get previous tag"
        id: latest-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.latest-tag.outputs.tag }}
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}
